import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Provider } from "react-redux";
import { store } from "../redux/store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`antialiased`}
        suppressHydrationWarning={true}
      >
        <Provider store={store}>
          <ThemeProvider defaultTheme="light">{children}</ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
